# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SuryoLingo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SuryoLingo
  pod 'AppCenter/Push', '~> 1.3.0'
  pod 'AppCenter/Analytics', '~> 1.3.0'
  pod 'AppCenterReactNativeShared', '~> 1.2.0'

  

  target 'SuryoLingoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SuryoLingo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SuryoLingo-tvOS

  target 'SuryoLingo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
