# Uncomment the next line to define a global platform for your project
platform :ios, "9.0"

target "SuryoLingo" do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod "yoga", path: "../node_modules/react-native/ReactCommon/yoga"
  pod "React", path: "../node_modules/react-native", :subspecs => [
             "Core",
             "CxxBridge",
             "RCTBlob",
             "DevSupport", # Include this to enable In-App Devmenu if RN >= 0.43
           # Add any other subspecs you want to use in your project
           ]

  # Pods for SuryoLingo
  pod "Fabric", "~> 1.7.5"
  pod "Crashlytics", "~> 3.10.1"
  pod "Google-Mobile-Ads-SDK"
  pod "react-native-fbsdk", :path => "../node_modules/react-native-fbsdk"
  pod "react-native-version-check", :path => "../node_modules/react-native-version-check"
  pod "RNDeviceInfo", :path => "../node_modules/react-native-device-info"
  pod "Folly", :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  pod "Firebase/Core"
  pod "Firebase/Messaging"
 
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
    fix_fb
  end

  def fix_fb
    node_modules_path = '../node_modules'
    patched_text = File.read("./RCTFBSDKLoginButtonManager.m.patch")

    File.open("#{node_modules_path}/react-native-fbsdk/ios/RCTFBSDK/login/RCTFBSDKLoginButtonManager.m", "w") {|file| file.puts patched_text}
  end

  platform :ios, "9.0"

  target "SuryoLingoTests" do
    inherit! :search_paths
    # Pods for testing
  end
end

target "SuryoLingo-tvOS" do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SuryoLingo-tvOS

  target "SuryoLingo-tvOSTests" do
    inherit! :search_paths
    # Pods for testing
  end
end
